#-------------------------------
# General Site Settings
title: Isaac Leonardo M.
logo: logo.svg # You can add own logo.
description: El blog personal de Isaac.


#-------------------------------
# Author Settings
author:
  name: Isaac Leonardo M.
  image: https://i.imgur.com/pVI0Opa.png
  say-hello: Hola, soy <strong>Isaac <span class='no-display'>Leonardo M.</span></strong>
  bio: Me dedico a crear y a escribir mis pensamientos y emociones, a transmitir con palabras lo que la mente no quiere callar.


#-------------------------------
# Contact links
twitter: https://twitter.com/isaaleonardo
telegram: https://t.me/isaaleonardo
instagram: https://instagram.com/isaaleonardo


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
